### PR TITLE
included commentary in trybe.js

### PR DESCRIPTION
**Pull request by tiagaoalb**
First pull request created as part of exercise 2.2 from Trybe course.

### CODE REVIEW

**Comment by MuriloBatista** [comment]
Parabéns pelo progresso!

**Review by PPiquini — COMMENTED** [review]
Isso ai! Sucesso!

**Comment by rosids** [comment]
Muito bacana, parabéns! #VQV

**Comment by wagnermor** [comment]
# Go Tryber! ;)

**Comment by Hugobrr** [comment]
Well done for completing this task!

**Comment by devtrybe** [comment]
You'll never forget the first pull request.

**Pull request merged**
