### PR TITLE
added bloco_3 folder

### PR DESCRIPTION
**Pull request by tiagaoalb**
Did this exercise to consolidate some HTML we learned at block 3_1. Hope you enjoy!

### CODE REVIEW

**Comment by Ludilly** [comment]
Excelent, Tiago! 
You are doing an amazing job!

**Comment by wagnermor** [comment]
🤟🏿

**Comment by RuaniFilipe** [comment]
Muito bom

**Comment by Doug-Fernando** [comment]
Nice :) #VQV

**Comment by Alanasreis** [comment]
Muito bom tiagao!!

**Comment by gabrielmaxgb** [comment]
Keep at this rate, ou did awesome!

**Pull request merged**
